name: CI demo

on: push


jobs:
    lint: 
        runs-on: ${{matrix.os}}

        strategy:
          matrix:
            os: [ubuntu-latest, windows-latest, macos-latest]
            python-version: ['3.9','3.10','3.11']

        steps:
            - name: Chcekout code
              uses: actions/checkout@v3
              with:
                python-version: ${{matrix.python-version}}

            - name: Setup Python
              uses: actions/setup-python@v4

            - name: Intall dependencies
              run: |
                python -m pip install --upgrade pip
                pip install flake8
                
            - name: Run flake8
              run: |
                flake8 example.py

